version: '3.8'

services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - ganache
    env_file:
      - .env
    environment:
      - PROVIDER=http://ganache:8545

  ganache:
    image: trufflesuite/ganache-cli
    container_name: ganache_node
    command: >
      --mnemonic "test test test test test test test test test test test junk"
      --port 8545
      --networkId 5777
    ports:
      - "8545:8545"